# These are supported funding model platforms

# github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: onelanguage
open_collective: onelang
ko_fi: onelang
# tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
# community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: one
issuehunt: One-Language
otechie: one
custom: ['https://www.buymeacoffee.com/onelang']
